### ISSUE TITLE
consider adding installation instructions

### ISSUE THREAD

**Issue by matkoniecz** [yaml/yaml-editor#19]

**Comment by perlpunk** [comment]
I agree that the README is a bit sparse.
Can you tell us where exactly you have problems installing? If you only want to use the pregenerated docker image, you only need bash and docker installed.

**Comment by matkoniecz** [comment]
I was looking for yaml editor, this repo appeared in search results.

I opened page, looked at readme, noticed lack of any info how it can be installed so I skipped this program.
